config/routes.rb
Rails.application.routes.draw do
  get 'rows_validator/initialize'
  get 'rows_validator/validate'
  get 'rows_validator/errors'
  resources :csv_files
  resources :contacts
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "csv_files#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/csv_file.rb
class CsvFile < ApplicationRecord
  belongs_to :user
  has_one_attached :doc
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :contacts
  has_many :csv_files
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new 
    #@contacts = CsvFiles.find(id)
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.fetch(:contact, {})
    end
end

app/controllers/csv_files_controller.rb
class CsvFilesController < ApplicationController
  before_action :set_csv_file, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /csv_files
  # GET /csv_files.json
  def index
    @csv_files = current_user.csv_files.all.order('created_at DESC')
  end

  # GET /csv_files/1
  # GET /csv_files/1.json
  def show
  end

  # GET /csv_files/new
  def new
    @csv_file = current_user.csv_files.build
  end

  # GET /csv_files/1/edit
  def edit
  end

  # POST /csv_files
  # POST /csv_files.json
  def create
    #render plain: params[:no_model_fields]
    require 'csv'
    @data = params[:csv_file]
    @headers = params[:no_model_fields].permit(params[:no_model_fields].keys).to_h
    @headers = @headers.sort_by{|k,v| v}
    @headers = [@headers[0][0], @headers[1][0], @headers[2][0], @headers[3][0], @headers[4][0], @headers[5][0]]
    #render plain: headers
    rows = proccess_data @data
    #CSV.foreach(@data[:doc].path, headers: headers, col_sep: ';') do |row|
      #contact = current_user.contacts.new(row.to_hash)
      #contact.save
    #  rows << row.to_hash
    #end
    #render plain: rows[0]["name"]
    #render plain: rows
    @csv_file = current_user.csv_files.new(csv_file_params)
    count = 1
    @errors = []
    rows.each do |row|
      if count != 1
        validate = RowsValidatorController.new(row)
        validate.validates 
        error = validate.errors 
        if !error.empty?
          @errors << error + " Linea " + count.to_s
        end
      end
      count = count + 1
    end

    #render plain: @errors
    
    
    #proccess_data(@data)
    if @errors.empty?
      if @csv_file.save
        count = 0
        rows.each do |row|
          if count != 0
            contact = current_user.contacts.new(row)
            contact.save
          end
          count = 1
        end
        redirect_to @csv_files_path, notice: 'Csv file was successfully created.' 
      else
        render :new 
      end
    else
      @csv_file.status = "Fallido"
      @csv_file.file_errors = @errors.to_s
      @csv_file.save
      redirect_to @csv_file, notice: 'Csv file was created with errors.'
      #render plain: csv_file_params
      #render plain: @errors.to_s
    end
  end

  # PATCH/PUT /csv_files/1
  # PATCH/PUT /csv_files/1.json
  def update
    respond_to do |format|
      if @csv_file.update(csv_file_params)
        format.html { redirect_to @csv_file, notice: 'Csv file was successfully updated.' }
        format.json { render :show, status: :ok, location: @csv_file }
      else
        format.html { render :edit }
        format.json { render json: @csv_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /csv_files/1
  # DELETE /csv_files/1.json
  def destroy
    @csv_file.destroy
    respond_to do |format|
      format.html { redirect_to csv_files_url, notice: 'Csv file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_csv_file
      @csv_file = CsvFile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def csv_file_params
      params.require(:csv_file).permit(:status, :file_errors, :doc)
    end

    def proccess_data(data)
      require 'csv'
      rows = []
      CSV.foreach(data[:doc].path, headers: @headers, col_sep: ';') do |row|
        #contact = current_user.contacts.new(row.to_hash)
        #contact.save
        rows << row.to_hash
      end
      return rows
    end
end

app/controllers/rows_validator_controller.rb
class RowsValidatorController < ApplicationController
  def initialize(row)
    @row = row.with_indifferent_access
    @errors = []
  end

  def validates
    if @row['name'].blank?
      @errors << 'El nombre no puede estar vacio'
    end
    if !/^[a-zA-Z0-9]+([- ][a-zA-Z0-9]+)*$/.match(@row['name'])
      @errors << 'El nombre no cumple con el formato requerido'
    end
    if !@row['dob'].match(/\d{4}-\d{2}-\d{2}/)
      @errors << 'El formato de la fecha no es valido'
    end
    if !@row['telephone'].match(/\+\d{2}[- ]\d{3}[- ]\d{3}[- ]\d{2}[- ]\d{2}/)
      @errors << 'El formato de telefono no es valido'
    end
    if !/^[^@]+@[^@]+\.[a-zA-Z]{2,}$/.match(@row['email'])
      @errors << 'El formato de email no es valido'
    end
    card = cardvalidate @row['credit_card']
    if card == 'false'
      @errors << 'La tarjeta no corresponde con ninguna de las franquicias validas'
      #@errors << 'Tarjeta de credito ' + @row['credit_card'].to_s + ' Tiene una longitud de '+ @row['credit_card'].delete(' ').length.to_s + ' y empieza por '+ @row['credit_card'][0..3]
    end
    
  end

  def cardvalidate(card)
    card = card.to_s
    if (card[0..1] == '34' || card[0..1] == '37') && card.delete(' ').length ==15
      return 'American Express'
    elsif ('3528'..'3589').to_a.include?(card[0..3]) && (card.delete(' ').length >= 16 && card.delete(' ').length <= 19)
      return 'JCB'
    elsif (('2221'..'2720').include?(card[0..3]) || ('51'..'55').include?(card[0..1])) && card.delete(' ').length == 16
      return 'Mastercard'
    elsif card[0] == '4' && card.delete(' ').length == 16
      return 'Visa'
    elsif (card.length >= 14 && card.delete(' ').length <= 19)
      return 'Diners'
    else
      return 'false'
    end
  end

  def errors
    @errors.join('. ')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/csv_files_helper.rb
module CsvFilesHelper
end

app/helpers/rows_validator_helper.rb
module RowsValidatorHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="3">Nombre</th>
      <th colspan="3">Fecha De Nacimiento</th>
      <th colspan="3">Telefono</th>
      <th colspan="3">Direccion</th>
      <th colspan="3">Tarjeta de Credito</th>
      <th colspan="3">Franquicia</th>
      <th colspan="3">Email</th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td colspan="3"><%= contact.name %></td>
        <td colspan="3"><%= contact.dob %></td>
        <td colspan="3"><%= contact.telephone %></td>
        <td colspan="3"><%= contact.address %></td>
        <td colspan="3"><%= contact.credit_card %></td>
        <td colspan="3"><%= contact.franchise %></td>
        <td colspan="3"><%= contact.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/csv_files/_form.html.erb
<%= simple_form_for(@csv_file) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/csv_files/edit.html.erb
<h1>Editing Csv File</h1>

<%= render 'form', csv_file: @csv_file %>

<%= link_to 'Show', @csv_file %> |
<%= link_to 'Back', csv_files_path %>

app/views/csv_files/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
        <p id="notice"><%= notice %></p>

        <h2 class="title is-2">Csv Files</h2>

        <table class="table">
          <thead>
            <tr>
              <th><abbr title="id">Id</abbr></th>
              <th><abbr title="name">Archivo</abbr></th>
              <th><abbr title="status">Estado</abbr></th>
              <th><abbr title="errors">Errores</abbr></th>
              <th><abbr title="proccess">Procesar</abbr></th>
            </tr>
          </thead>
          <tbody>
            <% @csv_files.each do |csv_file| %>
              <tr>
                <th><%= csv_file.id %></th>
                <td><%= csv_file.doc.filename %></td>
                <td><%= csv_file.status %></td>
                <td><%= csv_file.file_errors %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <br>

        <%= link_to 'New Csv File', new_csv_file_path %>
      </div>
    </div>
  </div>
</section>

app/views/csv_files/new.html.erb
<section class="section">
  <div class="container is-fluid">
    <div class="notification">
      <h2 class="title is-4">Archivos</h2>
      <%= simple_form_for(@csv_file) do |f| %>
        <%= f.hidden_field :status, value: "Procesando" %>
        <%= f.hidden_field :file_errors, value: " " %>
        <%= simple_fields_for :no_model_fields do |n| %>
          <div class="field">
            <p class="paragraph">Ingresar en los campos a continuacion el numero de columna correspondiente a los datos iniciando por 1.</p>
            <br/>
            <div class="control">
              <%= n.input :name, label: "Nombre", input_html: { class: "text "}, wrapper: false, label_html: {class: "label"}, placeholder: "Posicion nombre..." %>
            </div>
          </div>
          <div class="field">
            <div class="control">
              <%= n.input :dob, label: "Fecha de Nacimiento", input_html: { class: "text "}, wrapper: false, label_html: {class: "label"}, placeholder: "Posicion fecha de nacimiento..." %>
            </div>
          </div>
          <div class="field">
            <div class="control">
              <%= n.input :telephone, label: "Telefono", input_html: { class: "text "}, wrapper: false, label_html: {class: "label"}, placeholder: "Posicion Telefono..." %>
            </div>
          </div>
          <div class="field">
            <div class="control">
              <%= n.input :address, label: "Direccion", input_html: { class: "text "}, wrapper: false, label_html: {class: "label"}, placeholder: "Posicion Direccion..." %>
            </div>
          </div>
          <div class="field">
            <div class="control">
              <%= n.input :credit_card, label: "Tarjeta de Credito", input_html: { class: "text "}, wrapper: false, label_html: {class: "label"}, placeholder: "Posicion TC..." %>
            </div>
          </div>
          <div class="field">
            <div class="control">
              <%= n.input :email, label: "Email", input_html: { class: "text "}, wrapper: false, label_html: {class: "label"}, placeholder: "Posicion Email..." %>
            </div>
          </div>
        <% end %>
        <div class="field">
          <br/>
          <p class="paragraph">Seleccionar el archivo a importar :</p>
          <div class="control">
            <%= f.file_field :doc %>
          </div>
        </div>
        <br />
        <%= f.button :submit, 'Importar', class: "button is-info" %>
      <% end %>
    </div>
  </div>
</section>

app/views/csv_files/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_csv_file_path(@csv_file) %> |
<%= link_to 'Back', csv_files_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactosV4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar is-info">
  		<div class="navbar-brand">
  		<%= link_to contacts_path, class: "navbar-item" do %>
  			<h1 class="title is-4">Contacts</h1>
  		<% end %>
			<div class="navbar-burger burger" data-target="navbarExample">
					<span></span>
					<span></span>
					<span></span>
  		</div>
  	 </div>

			<div id="navbarExample" class="navbar-menu">
				<div class="navbar-end">
          <div class="navbar-item">
					<div class="field is-grouped">
            <% if user_signed_in? %>
              <p class="control">
                <%= link_to 'Archivos', csv_files_path, class: "button is-info" %>
              </p>
              <p class="control">
                <%= link_to 'Contactos', contacts_path, class: "button is-info" %>
              </p>
              <p class="control">
                <%= link_to current_user.email, edit_user_registration_path, class: "button is-info" %>
              </p>
              <p>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"button is-info" %>
              </p>
            <% else %>
            <p class="control">
              <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
            </p>
						<p class="control">
              <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
            </p>
            <% end %>
            </div>
					</div>
				</div>
			</div>
  	</nav>
    <div class="container">
        <%= yield %>
    </div>
  </body>
</html>

app/views/rows_validator/errors.html.erb
<h1>RowsValidator#errors</h1>
<p>Find me in app/views/rows_validator/errors.html.erb</p>

app/views/rows_validator/initialize.html.erb
<h1>RowsValidator#initialize</h1>
<p>Find me in app/views/rows_validator/initialize.html.erb</p>

app/views/rows_validator/validate.html.erb
<h1>RowsValidator#validate</h1>
<p>Find me in app/views/rows_validator/validate.html.erb</p>